# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.10.0"

pre_release = true

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.11/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]

    [notes.updates]
        title = "Component Updates"
        description = """\
ZFS: 2.3.2
qemu-guest-agent: 10.0.0
fuse: 3.17.2
nut: 2.8.3
Tailscale: 1.82.5        
"""

    [notes.youki]
        title = "Youki Container Runtime"
        description = """\
[Youki](https://github.com/youki-dev/youki) is now supported as a container runtime.
"""

[make_deps]
